# Configuration for Alacritty terminal emulator

# shell:
#   program: /usr/bin/env
#   args:
#     - zsh

window:
  # window padding (change requires restart)
  padding:
    x: 2
    y: 2
  # spread additional padding evenly around the terminal content
  dynamic_padding: true
  # window decoarations
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - (macos) transparent: title bar, transparent background, and title bar buttons
  # - (macos) buttonless: title bar transparent background, but no title bar buttons
  decorations: none
  # dynamically set the window title
  dynamic_title: true
  # Startup mode
  # - Windowed
  # - Maximized
  # - Fullscreen
  # - SimpleFullscreen (macos only)
  startup_mode: Maximized

scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  # Point size
  size: 20.0
  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  # thin stroke font rendering (macos)
  # Thin strokes is suitable for retina displays. Set to false for non-retina
  use_thin_strokes: true
  # draw bold text with bright color variants
  draw_bold_text_with_bright_colors: true

# Colors (Horizon Dark)
schemes:
colors:
  # Primary colors
  primary:
    background: '0x1c1e26'
    foreground: '0xe0e0e0'
  # Normal colors
  normal:
    black: '0x16161c'
    red: '0xe95678'
    green: '0x29d398'
    yellow: '0xfab795'
    blue: '0x26bbd9'
    magenta: '0xee64ac'
    cyan: '0x59e1e3'
    white: '0xd5d8da'
  # Bright colors
  bright:
    black: '0x5b5858'
    red: '0xec6a88'
    green: '0x3fdaa4'
    yellow: '0xfbc3a7'
    blue: '0x3fc4de'
    magenta: '0xf075b5'
    cyan: '0x6be4e6'
    white: '0xd5d8da'

mouse:
  # hide the cursor when typing
  hide_when_typing: true
  # save selected text to system clipboard
  save_to_clipboard: true
cursor:
  # Cursor style
  # - ▇ Block
  # - _ Underline
  # - | Beam
  style: Block
  # render the cursor as a hollow box when window is not focused
  unfocused_hollow: true

# automatically reload config upon change
live_config_reload: true

# set the backgeround opacity
window_opacity: 0.97
