#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5
#define _LAYER6 6
#define _LAYER7 7
#define _LAYER8 8

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
    LAYER6,
    LAYER7,
    LAYER8,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(KC_Q, LT(5,KC_W), LT(7,KC_E), KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, LT(1,KC_S), LT(8,KC_D), LT(3,KC_F), KC_G, KC_H, LT(4,KC_J), KC_K, KC_L, KC_SCLN, LSFT_T(KC_Z), LCTL_T(KC_X), LALT_T(KC_C), LGUI_T(KC_V), KC_B, KC_N, RGUI_T(KC_M), RALT_T(KC_COMM), RCTL_T(KC_DOT), RSFT_T(KC_SLSH), KC_LBRC, KC_BSPC, LT(6,KC_SPC), KC_QUOT),

[_LAYER1] = LAYOUT(KC_LPRN, KC_LCTL, KC_RPRN, KC_LT, KC_GT, KC_PPLS, KC_P7, KC_P8, KC_P9, KC_PSLS, KC_DLR, KC_NO, KC_DOT, KC_COMM, KC_PERC, KC_PMNS, KC_P4, KC_P5, KC_P6, KC_PAST, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_HASH, KC_EQL, KC_P1, KC_P2, KC_P3, LSFT(KC_QUOT), KC_LCTL, KC_TRNS, KC_TRNS, KC_P0),

[_LAYER2] = LAYOUT(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_LSFT, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_INS, KC_HOME, KC_PGUP, KC_BSPC, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_DEL, KC_END, KC_PGDN, KC_ESC, KC_SPC, KC_TAB, KC_TRNS, KC_ENT),

[_LAYER3] = LAYOUT(KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_GRV, KC_INT1, KC_TILD, KC_NO, KC_QUES, KC_MINS, KC_UNDS, KC_INT1, RSFT(KC_NUBS), KC_NUBS, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_PIPE, KC_AT, KC_EXLM, LSFT(KC_INT1), KC_HASH, KC_PERC, KC_LGUI, KC_TRNS, KC_SPC, KC_DLR),

[_LAYER4] = LAYOUT(KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_LT, KC_GT, KC_LPRN, KC_RPRN, KC_TILD, KC_TRNS, KC_NO, KC_MINS, KC_UNDS, KC_EQL, LSFT(KC_RBRC), LSFT(KC_NUHS), KC_RBRC, KC_NUHS, KC_GRV, KC_TRNS, KC_RGUI, KC_RALT, KC_RCTL, KC_RSFT, KC_AMPR, KC_TRNS, KC_SPC, KC_RGUI),

[_LAYER5] = LAYOUT(KC_LSFT, KC_NO, KC_LALT, KC_LGUI, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6, KC_F11, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F12, KC_LCTL, KC_TRNS, KC_SPC, KC_TRNS),

[_LAYER6] = LAYOUT(KC_PSCR, KC_INS, KC_PAUS, KC_ESC, KC_VOLU, DF(2), KC_WBAK, KC_WREF, KC_WFWD, KC_DEL, KC_CAPS, KC_NUM, KC_SCRL, KC_ENT, KC_VOLD, DF(1), KC_APP, KC_WHOM, KC_WSCH, QK_BOOT, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_MUTE, DF(0), KC_RGUI, KC_RALT, KC_RCTL, KC_RSFT, KC_BSPC, KC_TAB, KC_NO, KC_SPC),

[_LAYER7] = LAYOUT(KC_LSFT, KC_LCTL, KC_NO, KC_LGUI, KC_TRNS, KC_PGUP, KC_HOME, KC_UP, KC_END, KC_HOME, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_RGUI, KC_RALT, KC_RCTL, KC_RSFT, KC_LALT, KC_TRNS, KC_SPC, KC_TRNS),

[_LAYER8] = LAYOUT(KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_TRNS, KC_WH_U, KC_BTN1, KC_MS_U, KC_BTN2, KC_BTN4, KC_PMNS, KC_BTN2, KC_NO, KC_BTN1, KC_PPLS, KC_WH_D, KC_MS_L, KC_MS_D, KC_MS_R, KC_BTN5, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_TRNS, KC_BTN3, KC_WH_L, KC_BTN3, KC_WH_R, KC_TRNS, KC_LALT, KC_TRNS, KC_SPC, KC_TRNS) 

};

uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LSFT_T(KC_Z):
            return 135;
        case RSFT_T(KC_SLSH):
            return 135;
        case LT(1, KC_S):
            return 135;
        case LT(3, KC_F):
            return 135;
        case LT(4, KC_J):
            return 135;
        default:
            return TAPPING_TERM;
    }
};