return {
    -- system icons
    linux = " ",
    macos = " ",
    windows = " ",
    -- diagnostic icons
    -- error = "",
    error = " ",
    warning = "",
    warning_sign = " ",
    info = "",
    info_sign = " ",
    -- hint = "",
    hint = "󰠠 ",
    -- hint = "",
    lsp = "",
    line = "☰",
    -- git icons
    git = "",
    unstaged = "●",
    staged = "✓",
    unmerged = "",
    renamed = "➜",
    untracked = "★",
    ignored = "◌",
    modified = "",
    deleted = "",
    added = "",
    -- file icons
    arrow_open = "",
    arrow_closed = "",
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink_open = "",
    file = "",
    symlink = "",
    file_readonly = "",
    file_modified = "",
    -- misc
    devil = "",
    bsd = "",
    ghost = ""
}
